services:
  app:
    build: .
    container_name: app
    volumes:
      - ./res:/app/res
    environment:
      - OLLAMA_URL=http://192.168.30.50:31134
      - MODEL=qwen3-vl:30b
      - PDF_DIR=/app
      - RES_DIR=/app/res
    command: ["python", "main.py"]
